# Generated by Django 4.1.2 on 2022-10-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='words',
            name='pronunciation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
